api_version: go1
runtime: go

handlers:

- url: /
  static_files: static/index.html
  secure: always
  login: admin
  upload: static/index.html

- url: /index.html
  static_files: static/index.html
  secure: always
  login: admin
  upload: static/index.html

- url: /static/
  static_dir: static
  secure: always

- url: /.*
  script: _go_app
  secure: always
  login: admin

- url: /config
  static_dir: config
  application_readable: true
  secure: always
  login: admin
